### PR TITLE
Fix spelling mistake and remove debugging statement

### PR DESCRIPTION
**Pull request by joshuapatel**
This PR fixes a spelling issue and removes a call to the `print` method used for debugging.

I highly recommend looking over your code before you push directly to `master`. Submitting a pull request would be preferable so that the community can notice these issues before it's too late.

Cheers!

### CODE REVIEW

**Comment by GavynStanley** [comment]
This breaks the wrapper with the new spelling

**Comment by joshuapatel** [comment]
Can you please elaborate? If you read the code, I made an alias for the misspelled version of the word. Additionally, I fixed where the code was trying to get a non-existent key from the API's response. I'm assuming that the response from the API already has the correct spelling [after looking at the documentation](https://blist.xyz/docs#get-reviews).

**Comment by GavynStanley** [comment]
The wrapper is attempting to get a recommended value when it does not exists. It is in the db as recomended and I am not fixing it at the moment.

**Comment by joshuapatel** [comment]
I would highly advise that you fix your documentation to use the spelling as returned by the API. It is very confusing for library developers who assume that you check your spelling before you make releases AND when your documentation shows the correct spelling. There's a great extension for Visual Studio Code which [checks your spelling for you](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker). I personally use it and it works well.

Anyways, I made a change where it is now parsing the misspelled version of the word from the API. Let me know if there's anything else you would like to be changed.

Thanks!

**Comment by GavynStanley** [comment]
I have an extension for spell checking that I recently installed.

**Comment by joshuapatel** [comment]
Good to hear. You can merge this PR if you're ready to. Otherwise, let me know if you would like anything else to be fixed.

**Pull request merged**
